#TensorFlow

In TensorFlow computation is represented as a data flow graph where a node is an operation like addition and edge is a tensor.
Tensor is a Multidimensional Array


In [ ]:
import tensorflow as tf

#Initialization Of Tensors

In [ ]:
x = tf.constant(7)
print(x)

tf.Tensor(7, shape=(), dtype=int32)


In [ ]:
x = tf.constant(34, shape=(1,1))
print(x)

tf.Tensor([[34]], shape=(1, 1), dtype=int32)


In [ ]:
x = tf.constant(5, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[5.]], shape=(1, 1), dtype=float32)


In [ ]:
x = tf.constant([[2,6],[7,1]])
print(x)

tf.Tensor(
[[2 6]
 [7 1]], shape=(2, 2), dtype=int32)


In [ ]:
x = tf.ones((2,2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
x = tf.zeros((3,1))
print(x)

tf.Tensor(
[[0.]
 [0.]
 [0.]], shape=(3, 1), dtype=float32)


In [ ]:
x = tf.eye(2)
print(x)

tf.Tensor(
[[1. 0.]
 [0. 1.]], shape=(2, 2), dtype=float32)


In [ ]:
x = tf.random.normal((4,4), mean=0, stddev=1)#Values from normal distribution
print(x)

tf.Tensor(
[[-0.45270252 -2.034286    0.01172357  0.29522705]
 [ 1.4993254   0.41535816  0.69211304  0.785851  ]
 [ 0.47429836  1.8078505  -1.1244843   0.5481494 ]
 [ 0.68416256 -0.46542862 -0.4661939  -1.3952692 ]], shape=(4, 4), dtype=float32)


In [ ]:
x = tf.random.uniform((1,6), minval=-1, maxval=1)#Values from uniform distribution
print(x)

tf.Tensor([[ 0.10981631 -0.92959833  0.3190484   0.50576544 -0.50817966  0.77702665]], shape=(1, 6), dtype=float32)


In [ ]:
x = tf.range(5)
print(x)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [ ]:
x = tf.range(1,20,4)
print(x)

tf.Tensor([ 1  5  9 13 17], shape=(5,), dtype=int32)


In [ ]:
x = tf.cast(x, dtype=tf.float32)
print(x)

tf.Tensor([ 1.  5.  9. 13. 17.], shape=(5,), dtype=float32)


#Mathematical Operations

In [ ]:
x = tf.constant([6,4,1,9])
y = tf.constant([4,3,7,5])

z = tf.add(x,y)
a = x + y
print(z)
print(a)

tf.Tensor([10  7  8 14], shape=(4,), dtype=int32)
tf.Tensor([10  7  8 14], shape=(4,), dtype=int32)


In [ ]:
z = tf.subtract(x,y)
a = x - y
print(z)
print(a)

tf.Tensor([ 2  1 -6  4], shape=(4,), dtype=int32)
tf.Tensor([ 2  1 -6  4], shape=(4,), dtype=int32)


In [ ]:
z = tf.multiply(x,y)
a = x * y
print(z)
print(a)

tf.Tensor([24 12  7 45], shape=(4,), dtype=int32)
tf.Tensor([24 12  7 45], shape=(4,), dtype=int32)


In [ ]:
z = tf.divide(x,y)
a = x/y
print(z)
print(a)

tf.Tensor([1.5        1.33333333 0.14285714 1.8       ], shape=(4,), dtype=float64)
tf.Tensor([1.5        1.33333333 0.14285714 1.8       ], shape=(4,), dtype=float64)


In [ ]:
#Dot Product
z = tf.tensordot(x,y,axes=1)
a = tf.reduce_sum(x*y, axis=0)
print(z)
print(a)

tf.Tensor(88, shape=(), dtype=int32)
tf.Tensor(88, shape=(), dtype=int32)


In [ ]:
#Raise each element to the power 3
a = x**3
print(a)

tf.Tensor([216  64   1 729], shape=(4,), dtype=int32)


In [ ]:
x = tf.constant([[2,5],[3,4],[7,1]])
y = tf.constant([[5,2,6,7],[4,1,6,2]])
z = tf.matmul(x,y)
a = x @ y
print(z)
print(a)

tf.Tensor(
[[30  9 42 24]
 [31 10 42 29]
 [39 15 48 51]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[30  9 42 24]
 [31 10 42 29]
 [39 15 48 51]], shape=(3, 4), dtype=int32)


In [ ]:
x = tf.constant([[3,2,5],[4,5,1],[5,6,2]])
y = tf.constant([1,3,4], shape=(3,1))
z = tf.matmul(x,y)
print(z)
a = x @ y
print(a)

tf.Tensor(
[[29]
 [23]
 [31]], shape=(3, 1), dtype=int32)
tf.Tensor(
[[29]
 [23]
 [31]], shape=(3, 1), dtype=int32)


#Indexing

In [ ]:
x = tf.constant([0,4,65,3,5,2,6,4,5,1,8,9,4,6,7,2,3,7,1])
print(x[:])

tf.Tensor([ 0  4 65  3  5  2  6  4  5  1  8  9  4  6  7  2  3  7  1], shape=(19,), dtype=int32)


In [ ]:
print(x[3:])

tf.Tensor([3 5 2 6 4 5 1 8 9 4 6 7 2 3 7 1], shape=(16,), dtype=int32)


In [ ]:
print(x[1:5])

tf.Tensor([ 4 65  3  5], shape=(4,), dtype=int32)


In [ ]:
print(x[::2])

tf.Tensor([ 0 65  5  6  5  8  4  7  3  1], shape=(10,), dtype=int32)


In [ ]:
print(x[::-1])

tf.Tensor([ 1  7  3  2  7  6  4  9  8  1  5  4  6  2  5  3 65  4  0], shape=(19,), dtype=int32)


In [ ]:
ind = tf.constant([0,2,4,8])
z = tf.gather(x, ind)
print(z)

tf.Tensor([ 0 65  5  5], shape=(4,), dtype=int32)


In [ ]:
x = tf.constant([[4,5,1],[3,1,7],[9,3,2]])
print(x[0])

tf.Tensor([4 5 1], shape=(3,), dtype=int32)


In [ ]:
print(x[2])

tf.Tensor([9 3 2], shape=(3,), dtype=int32)


In [ ]:
#This notation is used when indexing a multidimensional tensor where the ',' seperates the dimensions
print(x[0,:])

tf.Tensor([4 5 1], shape=(3,), dtype=int32)


In [ ]:
print(x[0:2,:])

tf.Tensor(
[[4 5 1]
 [3 1 7]], shape=(2, 3), dtype=int32)


#Reshaping

In [ ]:
x = tf.range(1,10)
x = tf.reshape(x, (3,3))
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [ ]:
z = tf.transpose(x)
a = tf.transpose(x, perm=[1,0])
print(z)
print()
print(a)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)


#Neural Network

In [ ]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape)
print(y_train.shape)

11490434/11490434 [==============================] - 0s 0us/step
(60000, 28, 28)
(60000,)


In [ ]:
x_train = x_train.reshape(-1, 28*28).astype("float32") / 255.0
x_test = x_test.reshape(-1, 28*28).astype("float32") / 255.0
#Converting the data type from float64 to float 32 to reduce complex computations
#Normalizing the data by dividing by 255, which makes the range of values [0,1]
print(x_test.shape)

(10000, 784)


In [ ]:
#Defining The Model
# Sequential Api (one input, one output). Very convinient but not flexible
model = keras.Sequential(
    [
        keras.Input(shape=(28*28)), #only required to print the model summary before training
        layers.Dense(512, activation='relu'),
        layers.Dense(256, activation='relu'),
        layers.Dense(10),
    ]
)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train,y_train,batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 512)               401920    
                                                                 
 dense_1 (Dense)             (None, 256)               131328    
                                                                 
 dense_2 (Dense)             (None, 10)                2570      
                                                                 
Total params: 535818 (2.04 MB)
Trainable params: 535818 (2.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


None
Epoch 1/5
1875/1875 - 13s - loss: 0.5761 - accuracy: 0.8263 - 13s/epoch - 7ms/step
Epoch 2/5
1875/1875 - 14s - loss: 0.2909 - accuracy: 0.9139 - 14s/epoch - 8ms/step
Epoch 3/5
1875/1875 - 13s - loss: 0.2219 - accuracy: 0.9347 - 13s/epoch - 7ms/step
Epoch 4/5
1875/1875 - 13s - loss: 0.1760 - accuracy: 0.9477 - 13s/epoch - 7ms/step
Epoch 5/5
1875/1875 - 13s - loss: 0.1424 - accuracy: 0.9575 - 13s/epoch - 7ms/step
313/313 - 1s - loss: 0.1361 - accuracy: 0.9578 - 818ms/epoch - 3ms/step


[0.13613976538181305, 0.9577999711036682]

In [ ]:
#Another way of defining the layers
model = keras.Sequential()
model.add(layers.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
print(model.summary())
model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10))
print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train,y_train,batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 512)               401920    
                                                                 
 dense_4 (Dense)             (None, 256)               131328    
                                                                 
Total params: 533248 (2.03 MB)
Trainable params: 533248 (2.03 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 512)               401920    
                                                                 
 dense_4 (Dense)             (None, 256)               131328    
                                                         

None
Epoch 1/5
1875/1875 - 15s - loss: 0.6457 - accuracy: 0.7861 - 15s/epoch - 8ms/step
Epoch 2/5
1875/1875 - 14s - loss: 0.2738 - accuracy: 0.9173 - 14s/epoch - 7ms/step
Epoch 3/5
1875/1875 - 14s - loss: 0.1752 - accuracy: 0.9467 - 14s/epoch - 7ms/step
Epoch 4/5
1875/1875 - 15s - loss: 0.1351 - accuracy: 0.9583 - 15s/epoch - 8ms/step
Epoch 5/5
1875/1875 - 14s - loss: 0.1111 - accuracy: 0.9663 - 14s/epoch - 7ms/step
313/313 - 1s - loss: 0.1347 - accuracy: 0.9580 - 832ms/epoch - 3ms/step


[0.13469794392585754, 0.9580000042915344]

In [ ]:
#Functional Api (multiple inputs, multiple outputs). More flexible

inputs = keras.Input(shape=(28*28))
x = layers.Dense(512, activation='relu', name='1st_layer')(inputs)
x = layers.Dense(256, activation='relu', name='2nd_layer')(x)
output = layers.Dense(10, activation='softmax')(x)
model = keras.Model(inputs=inputs, outputs=output)

print(model.summary())

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
    optimizer=keras.optimizers.Adam(lr=0.001),
    metrics=["accuracy"],
)

model.fit(x_train,y_train,batch_size=32, epochs=5, verbose=2)
model.evaluate(x_test,y_test,batch_size=32,verbose=2)

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 784)]             0         
                                                                 
 1st_layer (Dense)           (None, 512)               401920    
                                                                 
 2nd_layer (Dense)           (None, 256)               131328    
                                                                 
 dense_14 (Dense)            (None, 10)                2570      
                                                                 
Total params: 535818 (2.04 MB)
Trainable params: 535818 (2.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


None
Epoch 1/5
1875/1875 - 13s - loss: 0.5933 - accuracy: 0.8188 - 13s/epoch - 7ms/step
Epoch 2/5
1875/1875 - 12s - loss: 0.2936 - accuracy: 0.9136 - 12s/epoch - 6ms/step
Epoch 3/5
1875/1875 - 12s - loss: 0.2247 - accuracy: 0.9340 - 12s/epoch - 7ms/step
Epoch 4/5
1875/1875 - 12s - loss: 0.1763 - accuracy: 0.9475 - 12s/epoch - 6ms/step
Epoch 5/5
1875/1875 - 12s - loss: 0.1438 - accuracy: 0.9569 - 12s/epoch - 7ms/step
313/313 - 1s - loss: 0.1321 - accuracy: 0.9602 - 765ms/epoch - 2ms/step


[0.13209010660648346, 0.9602000117301941]

In [ ]:
#Feature Extraction

model = keras.Sequential()
model.add(layers.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model = keras.Model(inputs=model.inputs, outputs=[model.layers[-2].output])
feature=model.predict(x_train)
print(feature.shape)

1875/1875 [==============================] - 6s 3ms/step
(60000, 256)


In [ ]:
#Feature Extraction

model = keras.Sequential()
model.add(layers.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu', name='intrestedLayer'))
model.add(layers.Dense(10, activation='softmax'))

model = keras.Model(inputs=model.inputs, outputs=[model.get_layer('intrestedLayer').output])
feature=model.predict(x_train)
print(feature.shape)

1875/1875 [==============================] - 5s 3ms/step
(60000, 256)


In [ ]:
#Feature Extraction

model = keras.Sequential()
model.add(layers.Input(shape=(28*28)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model = keras.Model(inputs=model.inputs, outputs=[layer.output for layer in model.layers])
features=model.predict(x_train)
for feature in features:
  print(feature.shape)

1875/1875 [==============================] - 7s 4ms/step
(60000, 512)
(60000, 256)
(60000, 10)
