In [28]:
import numpy as np
import re

In [29]:
filepath = "/kaggle/input/multihitmon/Vocabulary.txt"

In [30]:
with open(filepath, 'r') as file:
    text = file.read()

data = re.findall(r'\b[a-zA-Z]+\b', text)
data = [word.lower() for word in data]

words = list(set(data))

word_to_index = {word: idx for idx, word in enumerate(words)}

print(len(words))

5503


In [31]:
n = len(words)

word_counts = [data.count(word) for word in words]

C = np.zeros((n,n))


In [32]:
k=4

for i in range(n):
    current_word = data[i]
    if current_word not in word_to_index:
        continue
    current_index = word_to_index[current_word]
    
    # Define the window bounds
    start = max(i - k, 0)
    end = min(i + k + 1, n)
    
    # Update co-occurrence counts for words within the window
    for j in range(start, end):
        if i == j:
            continue  # Skip self-co-occurrence
        neighbor_word = data[j]
        if neighbor_word in word_to_index:
            neighbor_index = word_to_index[neighbor_word]
            C[current_index, neighbor_index] += 1

# Output the co-occurrence matrix
print("Co-Occurrence Matrix:")
print(C)

Co-Occurrence Matrix:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [33]:
C.trace()

388.0

In [34]:
for i in range(n):
    for j in range(n):
        val = min(C[i][j], 50)
        p_i_given_j = (val*n)/(word_counts[i]*word_counts[j])
        if p_i_given_j<1:
            PPMI = 0
        else:
            PPMI = np.log(p_i_given_j)
        
        C[i][j] = PPMI

print(C)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
C.trace()

106.96639224915772

In [36]:
U, S, Vt = np.linalg.svd(C)

print(f"{U.shape}, {S.shape}, {Vt.shape}")

S_full = np.zeros((U.shape[0], Vt.shape[0]))
np.fill_diagonal(S_full, S)



(5503, 5503), (5503,), (5503, 5503)


In [85]:
k = 3

U_k = U[:, :k]
S_k = S_full[:k, :k]
Vt_k = Vt[:k, :]


In [86]:
A = U_k @ S_k @ Vt_k
print(A)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.00101669 0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]


In [87]:
W = U_k @ S_k
print(W)
print(W.shape)

[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 ...
 [-0.22502532  0.01994475 -0.13296309]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]]
(5503, 3)


In [95]:
a = word_to_index["blushing"]
b = word_to_index["girl"]
print(f"{a} {b}")

165 5081


In [96]:
u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

0.9806482866128787


In [97]:
a = word_to_index["material"]
b = word_to_index["girl"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

61 5081
0.6565162532108972


In [98]:
a = word_to_index["smile"]
b = word_to_index["blushing"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

52 165
0.9361477902096179


In [99]:
a = word_to_index["smile"]
b = word_to_index["material"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

52 61
0.5853638896635801


In [100]:
a = word_to_index["smile"]
b = word_to_index["girl"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

52 5081
0.9728518126590507


In [101]:
a = word_to_index["maiden"]
b = word_to_index["girl"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

1170 5081
0.9844824918058355


In [102]:
a = word_to_index["son"]
b = word_to_index["child"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

970 1169
0.7112687302628838


In [103]:
a = word_to_index["material"]
b = word_to_index["equipment"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

61 2401
0.6420537388399026


In [104]:
a = word_to_index["equipment"]
b = word_to_index["tournament"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

2401 4330
0.9265566374780783


In [105]:
a = word_to_index["tournament"]
b = word_to_index["material"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

4330 61
0.739228340883525


In [106]:
a = word_to_index["woman"]
b = word_to_index["girl"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

4426 5081
0.99316053011656


In [107]:
a = word_to_index["smile"]
b = word_to_index["woman"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

52 4426
0.9606136026238464


In [108]:
a = word_to_index["blushing"]
b = word_to_index["woman"]
print(f"{a} {b}")

u = W[a]
v = W[b]

sim = (np.dot(u,v))/np.sqrt(np.dot(u,u)*np.dot(v,v))
print(sim)

165 4426
0.9963554962404101


In [88]:
def rows_with_nonzero(matrix):
    non_zero_rows = [i for i in range(len(matrix)) if any(matrix[i])]
    return non_zero_rows

non_zero_rows = rows_with_nonzero(W)

for i in non_zero_rows:
    print(f"{i}: {words[i]}")

5: favorite
6: beaten
7: seconds
8: among
9: nope
10: headache
11: crimson
12: mumbles
13: angrily
14: pretendin
15: balefully
16: aggravating
17: honor
18: penetrated
19: ughhhh
20: hand
21: block
22: obscure
23: haven
24: balls
25: before
26: charged
27: pictures
28: ordinary
29: twenty
30: response
31: strained
32: treasure
33: investigatory
34: performed
35: ack
36: million
37: colorful
38: stomach
39: group
40: nympha
41: candidate
42: knowing
43: deploy
44: slowed
46: more
48: purest
49: illustration
50: chewed
51: drinks
52: smile
54: virtual
55: flavor
57: standards
58: climbing
59: sufficed
61: material
62: actually
63: questioning
64: by
71: multi
73: lift
80: seems
83: vivid
95: dizzy
96: packs
102: hmm
107: paying
108: hurry
111: envelopes
120: elsewhere
129: gems
131: epilogue
132: assessing
133: dunno
135: pleasant
136: resurrection
139: worked
141: brains
146: bad
158: learned
163: they
165: blushing
166: blue
170: smiling
175: lunches
178: mentioned
179: timid
183: jv
1